apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-env
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/CHACHO617/ProyectoFinalProcesos
    targetRevision: HEAD
    path: k8s/test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
